default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: db/actioncablechat_development

test:
  <<: *default
  database: db/actioncablechat_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: actioncablechat_production
  username: actioncablechat
